export const cards = [
  {
    id: 1,
    title: "0.01 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin1.svg",
  },
  {
    id: 2,
    title: "0.02 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin2.svg",
  },
  {
    id: 3,
    title: "0.03 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin3.svg",
  },
  {
    id: 4,
    title: "0.03 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin4.svg",
  },
  {
    id: 5,
    title: "0.04 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin5.svg",
  },
  {
    id: 6,
    title: "0.05 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin6.svg",
  },
  {
    id: 7,
    title: "0.01 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin7.svg",
  },
  {
    id: 8,
    title: "0.02 SOL",
    type: "SOL",
    value: 0.05,
    chance: 0.1,
    image: "/images/coin8.svg",
  },
];
